name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main  # Change to 'master' if your default branch is 'master'

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install Dependencies
        run: npm install 

      - name: Build Angular Project
        run: ng build --configuration=production --base-href /Portfolio/  

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist/browser 
          token: ${{ secrets.GITHUB_TOKEN }}
          clean: true
          force: true
