name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - master  # Runs on push to main branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build Angular App
        run: ng build --output-path dist/browser --base-href /Portfolio/

      - name: Deploy to GitHub Pages
        run: npx angular-cli-ghpages --dir=dist/portfolio --no-silent